// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"mkanban/internal/application/strategy"
	"mkanban/internal/application/usecase/action"
	"mkanban/internal/application/usecase/board"
	"mkanban/internal/application/usecase/column"
	"mkanban/internal/application/usecase/session"
	"mkanban/internal/application/usecase/task"
	"mkanban/internal/domain/entity"
	"mkanban/internal/domain/repository"
	"mkanban/internal/domain/service"
	"mkanban/internal/infrastructure/config"
	"mkanban/internal/infrastructure/external"
	"mkanban/internal/infrastructure/persistence/filesystem"
	service2 "mkanban/internal/infrastructure/service"
)

// Injectors from wire.go:

// InitializeContainer sets up all dependencies
func InitializeContainer() (*Container, error) {
	config, err := ProvideConfig()
	if err != nil {
		return nil, err
	}
	boardRepository := ProvideBoardRepository(config)
	actionRepository := ProvideActionRepository(config)
	projectRepository := ProvideProjectRepository(config)
	timeLogRepository := ProvideTimeLogRepository(config)
	noteRepository := ProvideNoteRepository(config)
	validationService := ProvideValidationService(boardRepository)
	boardService := ProvideBoardService(boardRepository, validationService, config)
	sessionTracker := ProvideSessionTracker()
	vcsProvider := ProvideVCSProvider()
	changeWatcher, err := ProvideChangeWatcher()
	if err != nil {
		return nil, err
	}
	repoPathResolver := ProvideRepoPathResolver(sessionTracker, vcsProvider, projectRepository)
	v := ProvideBoardSyncStrategies(vcsProvider, config)
	sessionBoardPlanner := session.NewSessionBoardPlanner(vcsProvider)
	createBoardUseCase := board.NewCreateBoardUseCase(boardService)
	getBoardUseCase := board.NewGetBoardUseCase(boardRepository)
	listBoardsUseCase := board.NewListBoardsUseCase(boardRepository)
	createColumnUseCase := column.NewCreateColumnUseCase(boardService)
	createTaskUseCase := task.NewCreateTaskUseCase(boardService)
	moveTaskUseCase := task.NewMoveTaskUseCase(boardService)
	updateTaskUseCase := task.NewUpdateTaskUseCase(boardService)
	listTasksUseCase := task.NewListTasksUseCase(boardRepository, config)
	checkoutTaskUseCase := task.NewCheckoutTaskUseCase(boardRepository, vcsProvider, repoPathResolver)
	syncSessionBoardUseCase := session.NewSyncSessionBoardUseCase(boardRepository, projectRepository, boardService, v, sessionBoardPlanner)
	trackSessionsUseCase := session.NewTrackSessionsUseCase(sessionTracker, syncSessionBoardUseCase)
	getActiveSessionBoardUseCase := session.NewGetActiveSessionBoardUseCase(sessionTracker, boardRepository, syncSessionBoardUseCase, sessionBoardPlanner)
	createActionUseCase := action.NewCreateActionUseCase(actionRepository)
	updateActionUseCase := action.NewUpdateActionUseCase(actionRepository)
	deleteActionUseCase := action.NewDeleteActionUseCase(actionRepository)
	getActionUseCase := action.NewGetActionUseCase(actionRepository)
	listActionsUseCase := action.NewListActionsUseCase(actionRepository)
	enableActionUseCase := action.NewEnableActionUseCase(actionRepository)
	disableActionUseCase := action.NewDisableActionUseCase(actionRepository)
	evaluateActionsUseCase := action.NewEvaluateActionsUseCase(actionRepository, boardRepository)
	notifier := ProvideNotifier(config)
	scriptRunner := ProvideScriptRunner(config)
	taskMutator := ProvideTaskMutator(createTaskUseCase, updateTaskUseCase, moveTaskUseCase)
	executeActionUseCase := action.NewExecuteActionUseCase(actionRepository, notifier, scriptRunner, taskMutator)
	processEventUseCase := action.NewProcessEventUseCase(evaluateActionsUseCase, executeActionUseCase, actionRepository)
	eventBus := ProvideEventBus()
	container := &Container{
		Config:                       config,
		BoardRepo:                    boardRepository,
		ActionRepo:                   actionRepository,
		ProjectRepo:                  projectRepository,
		TimeLogRepo:                  timeLogRepository,
		NoteRepo:                     noteRepository,
		ValidationService:            validationService,
		BoardService:                 boardService,
		SessionTracker:               sessionTracker,
		VCSProvider:                  vcsProvider,
		ChangeWatcher:                changeWatcher,
		RepoPathResolver:             repoPathResolver,
		BoardSyncStrategies:          v,
		CreateBoardUseCase:           createBoardUseCase,
		GetBoardUseCase:              getBoardUseCase,
		ListBoardsUseCase:            listBoardsUseCase,
		CreateColumnUseCase:          createColumnUseCase,
		CreateTaskUseCase:            createTaskUseCase,
		MoveTaskUseCase:              moveTaskUseCase,
		UpdateTaskUseCase:            updateTaskUseCase,
		ListTasksUseCase:             listTasksUseCase,
		CheckoutTaskUseCase:          checkoutTaskUseCase,
		TrackSessionsUseCase:         trackSessionsUseCase,
		GetActiveSessionBoardUseCase: getActiveSessionBoardUseCase,
		SyncSessionBoardUseCase:      syncSessionBoardUseCase,
		CreateActionUseCase:          createActionUseCase,
		UpdateActionUseCase:          updateActionUseCase,
		DeleteActionUseCase:          deleteActionUseCase,
		GetActionUseCase:             getActionUseCase,
		ListActionsUseCase:           listActionsUseCase,
		EnableActionUseCase:          enableActionUseCase,
		DisableActionUseCase:         disableActionUseCase,
		EvaluateActionsUseCase:       evaluateActionsUseCase,
		ExecuteActionUseCase:         executeActionUseCase,
		ProcessEventUseCase:          processEventUseCase,
		EventBus:                     eventBus,
		Notifier:                     notifier,
		ScriptRunner:                 scriptRunner,
		TaskMutator:                  taskMutator,
	}
	return container, nil
}

// wire.go:

// Container holds all application dependencies
type Container struct {
	// Config
	Config *config.Config

	// Repositories
	BoardRepo   repository.BoardRepository
	ActionRepo  repository.ActionRepository
	ProjectRepo repository.ProjectRepository
	TimeLogRepo repository.TimeLogRepository
	NoteRepo    repository.NoteRepository

	// Domain Services
	ValidationService *service.ValidationService
	BoardService      *service.BoardService
	SessionTracker    service.SessionTracker
	VCSProvider       service.VCSProvider
	ChangeWatcher     service.ChangeWatcher
	RepoPathResolver  service.RepoPathResolver

	// Strategies
	BoardSyncStrategies []strategy.BoardSyncStrategy

	// Use Cases - Board
	CreateBoardUseCase *board.CreateBoardUseCase
	GetBoardUseCase    *board.GetBoardUseCase
	ListBoardsUseCase  *board.ListBoardsUseCase

	// Use Cases - Column
	CreateColumnUseCase *column.CreateColumnUseCase

	// Use Cases - Task
	CreateTaskUseCase   *task.CreateTaskUseCase
	MoveTaskUseCase     *task.MoveTaskUseCase
	UpdateTaskUseCase   *task.UpdateTaskUseCase
	ListTasksUseCase    *task.ListTasksUseCase
	CheckoutTaskUseCase *task.CheckoutTaskUseCase

	// Use Cases - Session
	TrackSessionsUseCase         *session.TrackSessionsUseCase
	GetActiveSessionBoardUseCase *session.GetActiveSessionBoardUseCase
	SyncSessionBoardUseCase      *session.SyncSessionBoardUseCase

	// Use Cases - Action
	CreateActionUseCase    *action.CreateActionUseCase
	UpdateActionUseCase    *action.UpdateActionUseCase
	DeleteActionUseCase    *action.DeleteActionUseCase
	GetActionUseCase       *action.GetActionUseCase
	ListActionsUseCase     *action.ListActionsUseCase
	EnableActionUseCase    *action.EnableActionUseCase
	DisableActionUseCase   *action.DisableActionUseCase
	EvaluateActionsUseCase *action.EvaluateActionsUseCase
	ExecuteActionUseCase   *action.ExecuteActionUseCase
	ProcessEventUseCase    *action.ProcessEventUseCase

	// Infrastructure Services
	EventBus     entity.EventBus
	Notifier     entity.Notifier
	ScriptRunner entity.ScriptRunner
	TaskMutator  entity.TaskMutator
}

func ProvideConfig() (*config.Config, error) {
	loader, err := config.NewLoader()
	if err != nil {
		return nil, err
	}
	return loader.Load()
}

func ProvideBoardRepository(cfg *config.Config) repository.BoardRepository {
	return filesystem.NewBoardRepository(cfg.Storage.DataPath)
}

func ProvideValidationService(boardRepo repository.BoardRepository) *service.ValidationService {
	return service.NewValidationService(boardRepo)
}

func ProvideBoardService(
	boardRepo repository.BoardRepository,
	validationService *service.ValidationService,
	cfg *config.Config,
) *service.BoardService {
	return service.NewBoardService(boardRepo, validationService, cfg)
}

func ProvideSessionTracker() service.SessionTracker {
	return external.NewTmuxSessionTracker()
}

func ProvideVCSProvider() service.VCSProvider {
	return external.NewGitVCSProvider()
}

func ProvideChangeWatcher() (service.ChangeWatcher, error) {
	return external.NewFSNotifyWatcher()
}

func ProvideRepoPathResolver(
	sessionTracker service.SessionTracker,
	vcsProvider service.VCSProvider,
	projectRepo repository.ProjectRepository,
) service.RepoPathResolver {
	return service2.NewTmuxRepoPathResolver(sessionTracker, vcsProvider, projectRepo)
}

func ProvideBoardSyncStrategies(
	vcsProvider service.VCSProvider,
	cfg *config.Config,
) []strategy.BoardSyncStrategy {
	strategies := make([]strategy.BoardSyncStrategy, 0)

	gitStrategy := strategy.NewGitRepoSyncStrategy(vcsProvider)
	strategies = append(strategies, gitStrategy)

	generalStrategy := strategy.NewGeneralSyncStrategy(cfg.SessionTracking.GeneralBoardName)
	strategies = append(strategies, generalStrategy)

	return strategies
}

func ProvideActionRepository(cfg *config.Config) repository.ActionRepository {
	return filesystem.NewActionRepository(cfg)
}

func ProvideEventBus() entity.EventBus {
	return service2.NewEventBus()
}

func ProvideNotifier(cfg *config.Config) entity.Notifier {
	return external.NewDesktopNotifier(cfg.Actions.NotificationsEnabled)
}

func ProvideScriptRunner(cfg *config.Config) entity.ScriptRunner {
	return external.NewScriptExecutor(cfg.Actions.ScriptsEnabled, cfg.Actions.ScriptsDir)
}

func ProvideTaskMutator(
	createTaskUseCase *task.CreateTaskUseCase,
	updateTaskUseCase *task.UpdateTaskUseCase,
	moveTaskUseCase *task.MoveTaskUseCase,
) entity.TaskMutator {
	return service2.NewTaskMutatorService(createTaskUseCase, updateTaskUseCase, moveTaskUseCase)
}

func ProvideProjectRepository(cfg *config.Config) repository.ProjectRepository {
	return filesystem.NewProjectRepository(cfg.Storage.DataPath)
}

func ProvideTimeLogRepository(cfg *config.Config) repository.TimeLogRepository {
	return filesystem.NewTimeLogRepository(cfg.Storage.DataPath)
}

func ProvideNoteRepository(cfg *config.Config) repository.NoteRepository {
	return filesystem.NewNoteRepository(cfg.Storage.DataPath)
}
